os: osx
osx_image: xcode9.2
language: swift
xcode_project: Browsy.xcodeproj # path to your xcodeproj folder
xcode_scheme: Browsy
script:
  - xcodebuild -scheme Browsy -configuration Release build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
